check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.0.15"
  build-stratergy: Source
  registry: quay.io
  registry-org: modh
  registry-project: odh-generic-data-science-notebook
  registry-secret: modh-pusher-secret
